### ISSUE TITLE
Lock screen is flickering

### ISSUE THREAD

**Issue by bookteo** [damianmqr/A9PatchingService#17]
After pressing the power button the lock screen is flickering. This is only visible if the fingerprint reader is not reacting fast enough, which happens to me all the time.

In the XDA Thread someone posted this link.
https://github.com/generalbrus/BrightLockscreen/blob/master/app/src/main/java/com/generalbrus/brightlockscreen/BrightLockscreen.java#L56

Apparently the lock screen has some kind of layer on top, that makes it flickering. Maybe it would be an option to remove the overlay.

**Comment by damianmqr** [comment]
The layer should now be removed.
