### ISSUE TITLE
Headphone jack is not working

### ISSUE THREAD

**Issue by wjvdb** [damianmqr/A9PatchingService#18]
I am running the version from https://xdaforums.com/t/hisense-a9-root-reward-offered-snapdragon-662.4495809/post-89618790

There is a slight issue that it doesn't fully detect the headphone. If I am playing spotify on my a9 it will say in the spotify notification: "playing through wired headphones" but it won't play through them.  The volume switch also doesn't indicate wired headphones but just the speaker. 
![Screenshot_20240729-091523_Spotify](https://github.com/user-attachments/assets/c200c5fe-ad63-484e-b0d5-d2fbe183ef90)
![Screenshot_20240729-091518_Spotify](https://github.com/user-attachments/assets/373a12ac-143b-469e-8422-1791b15c4791)
![Screenshot_20240729-091508_Spotify](https://github.com/user-attachments/assets/bed7aede-7e6c-455b-aa97-56abf1cae903)

**Comment by wjvdb** [comment]
never mind, I figured in "phh treble settings"-> "misc features" -> disable "Use alternate way to detect headsets". did the trick

**Comment by wjvdb** [comment]
Started again today now the settings dont influence it and Spotify does not detect it

**Comment by damianmqr** [comment]
> Started again today, now the settings dont influence it and Spotify does not detect it

Have you tried going to `Phh Treble Settings -> Qualcomm features` and disabling and then re-enabling Use Alternate Audio Policy?

**Comment by wjvdb** [comment]
Doing that did not help immediately, I had to restart the phone then it started working again (without toggling the switch).

**Comment by wjvdb** [comment]
This issue hasn't come up yet since, so I close it for now.
